import withIconColor from '@psycron/hoc/withIconColor';

import { Brand as IconBrand } from './brand/Brand';
import { Logo as IconLogo } from './brand/Logo';
export { LogoColor as IconLogoColor } from './brand/LogoColor';
import { Jupiter as IconJupiter } from './brand/Jupiter';
import { ChevronDown as IconChevronDown } from './chevron/ChevronDown';
import { ChevronLeft as IconChevronLeft } from './chevron/ChevronLeft';
import { ChevronRight as IconChevronRight } from './chevron/ChevronRight';
import { ChevronUp as IconChevronUp } from './chevron/ChevronUp';
import { EditUser as IconEditUser } from './user/EditUser';
import { SaveUser as IconSaveUser } from './user/SaveUser';
import { UserSettings as IconUserSettings } from './user/UserSettings';
import { Address as IconAddress } from './Address';
import { Alert as IconAlert } from './Alert';
import { Appointment as IconAppointment } from './Appointment';
import { Available as IconAvailable } from './Available';
import { Calendar as IconCalendar } from './Calendar';
import { CalendarOff as IconCalendarOff } from './CalendarOff';
import { CalendarRange as IconCalendarRange } from './CalendarRange';
import { CheckFail as IconCheckFail } from './CheckFail';
import { CheckSuccess as IconCheckSuccess } from './CheckSuccess';
import { Close as IconClose } from './Close';
import { DashboardIcon as IconDashboardIcon } from './DashboardIcon';
import { Dots as IconDots } from './Dots';
import { Error as IconError } from './Error';
import { Globe as IconGlobe } from './Globe';
import { HealthTracker as IconHealthTracker } from './HealthTracker';
import { Info as IconInfo } from './Info';
import { Lock as IconLock } from './Lock';
import { Mail as IconMail } from './Mail';
import { MapPin as IconMapPin } from './MapPin';
import { Month as IconMonth } from './Month';
import { Send as IconSend } from './Send';
import { Share as IconShare } from './Share';
import { Today as IconToday } from './Today';
import { UnAvailable as IconUnAvailable } from './UnAvailable';

export { Language } from './Language';

import { AddPatient as IconAddPatient } from './user/patient/AddPatient';
import { PatientList as IconPatientList } from './user/patient/PatientList';
import { PatientManager as IconPatientManager } from './user/patient/PatientManager';
import { RemovePatient as IconRemovePatient } from './user/patient/RemovePatient';
import { ClockIn as IconClockIn } from './ClockIn';
import { Copy as IconCopy } from './Copy';
import { Edit as IconEdit } from './Edit';
import { FilterIcon as IconFilter } from './Filter';
import { FilterCloseIcon as IconFilterClose } from './FilterClose';
import { HelpIcon as IconHelp } from './Help';
import { Login as IconLogin } from './Login';
import { Logout as IconLogout } from './Logout';
import { Menu as IconMenu } from './Menu';
import { Messenger as IconMessenger } from './Messenger';
import { Notifications as IconNotifications } from './Notifications';
import { NotVisible as IconNotVisible } from './NotVisible';
import { Password as IconPassword } from './Password';
import { Pause as IconPause } from './Pause';
import { Payment as IconPayment } from './Payment';
import { Phone as IconPhone } from './Phone';
import { Plan as IconPlan } from './Plan';
import { PlanPaid as IconPlanPaid } from './PlanPaid';
import { PlanUnpaid as IconPlanUnpaid } from './PlanUnpaid';
import { Play as IconPlay } from './Play';
import { SendInvoice as IconSendInvoice } from './SendInvoice';
import { Visible as IconVisible } from './Visible';
import { Watch as IconWatch } from './Watch';
import { WhatsApp as IconWhatsApp } from './Whatsapp';

export const Pause = withIconColor(IconPause);
export const Send = withIconColor(IconSend);
export const Globe = withIconColor(IconGlobe);
export const MapPin = withIconColor(IconMapPin);
export const ClockIn = withIconColor(IconClockIn);
export const Play = withIconColor(IconPlay);
export const Edit = withIconColor(IconEdit);
export const PatientManager = withIconColor(IconPatientManager);
export const Notifications = withIconColor(IconNotifications);
export const Help = withIconColor(IconHelp);
export const Address = withIconColor(IconAddress);
export const PatientList = withIconColor(IconPatientList);
export const RemovePatient = withIconColor(IconRemovePatient);
export const AddPatient = withIconColor(IconAddPatient);
export const Alert = withIconColor(IconAlert);
export const Appointment = withIconColor(IconAppointment);
export const Brand = withIconColor(IconBrand);
export const Logo = withIconColor(IconLogo);
export const Calendar = withIconColor(IconCalendar);
export const CalendarOff = withIconColor(IconCalendarOff);
export const CalendarRange = withIconColor(IconCalendarRange);
export const CheckFail = withIconColor(IconCheckFail);
export const CheckSuccess = withIconColor(IconCheckSuccess);
export const ChevronDown = withIconColor(IconChevronDown);
export const ChevronLeft = withIconColor(IconChevronLeft);
export const ChevronRight = withIconColor(IconChevronRight);
export const ChevronUp = withIconColor(IconChevronUp);
export const Close = withIconColor(IconClose);
export const DashboardIcon = withIconColor(IconDashboardIcon);
export const Error = withIconColor(IconError);
export const HealthTracker = withIconColor(IconHealthTracker);
export const Info = withIconColor(IconInfo);
export const Login = withIconColor(IconLogin);
export const Logout = withIconColor(IconLogout);
export const Menu = withIconColor(IconMenu);
export const NotVisible = withIconColor(IconNotVisible);
export const Password = withIconColor(IconPassword);
export const Payment = withIconColor(IconPayment);
export const Phone = withIconColor(IconPhone);
export const Plan = withIconColor(IconPlan);
export const PlanPaid = withIconColor(IconPlanPaid);
export const PlanUnpaid = withIconColor(IconPlanUnpaid);
export const SendInvoice = withIconColor(IconSendInvoice);
export const EditUser = withIconColor(IconEditUser);
export const SaveUser = withIconColor(IconSaveUser);
export const UserSettings = withIconColor(IconUserSettings);
export const Visible = withIconColor(IconVisible);
export const Filter = withIconColor(IconFilter);
export const FilterClose = withIconColor(IconFilterClose);
export const Available = withIconColor(IconAvailable);
export const UnAvailable = withIconColor(IconUnAvailable);
export const Share = withIconColor(IconShare);
export const Copy = withIconColor(IconCopy);
export const Lock = withIconColor(IconLock);
export const Today = withIconColor(IconToday);
export const WhatsApp = withIconColor(IconWhatsApp);
export const Watch = withIconColor(IconWatch);
export const Mail = withIconColor(IconMail);
export const Messenger = withIconColor(IconMessenger);
export const Dots = withIconColor(IconDots);
export const Month = withIconColor(IconMonth);
export const Jupiter = withIconColor(IconJupiter);
